<section id="rescue">
  <h3>Rescue</h3>

  <p>An executing program can run into unexpected problems.  A file
  that it wants to read might not exist; the disk might be full when
  it wants to save some data; the user may provide it with some
  unsuitable kind of input.</p>
  <p><div class=shell>ruby&gt;<font color="#ffff00"><b> file = open("some_file")</b></font><br>
  <font color="#50ffff"><b>ERR: (eval):1:in `open': No such file or directory - some_file</b></font></div>

  <p>A robust program will handle these situations sensibly and
  gracefully.  Meeting that expectation can be an exasperating
  task.  C programmers are expected to check the result of every
  system call that could possibly fail, and immediately decide what is
  to be done:</p>
  <p><div class=cscript>FILE *file = fopen("some_file", "r");<br>
  if (file == NULL) {<br>
  &nbsp; fprintf( stderr, "File doesn't exist.\n" );<br>
  &nbsp; exit(1);<br>
  }<br>
  bytes_read = fread( buf, 1, bytes_desired, file );<br>
  if (bytes_read != bytes_desired ) {<br>
  &nbsp; /* do more error handling here ... */<br>
  }<br>
  ...</div>

  <p>This is such a tiresome practice that programmers can tend to grow
  careless and neglect it, and the result is a program that doesn't
  handle exceptions well.  On the other hand, doing the job right
  can make programs hard to read, because there is so much error
  handling cluttering up the meaningful code.</p>
  <p>In ruby, as in many modern languages, we can handle exceptions for
  blocks of code in a compartmentalized way, thus dealing with surprises
  effectively but not unduly burdening either the programmer or anyone
  else trying to read the code later.  The block of code marked
  with <code>begin</code> executes until there is an exception, which causes
  control to be transferred to a block of error handling code, which is
  marked with <code>rescue</code>.  If no exception occurs, the
  <code>rescue</code> code is not used.  The following method returns
  the first line of a text file, or <code>nil</code> if there is an
  exception:</p>
  <p><div class=rbscript>def first_line( filename )<br>
  &nbsp; begin<br>
  &nbsp; &nbsp; file = open("some_file")<br>
  &nbsp; &nbsp; info = file.gets<br>
  &nbsp; &nbsp; file.close<br>
  &nbsp; &nbsp; info&nbsp; # Last thing evaluated is the return value<br>
  &nbsp; rescue<br>
  &nbsp; &nbsp; nil&nbsp;&nbsp; # Can't read the file? then don't return a string<br>
  &nbsp; end<br>
  end</div>

  <p>There will be times when we would like to be able to creatively
  work around a problem.  Here, if the file we want is unavailable,
  we try to use standard input instead:</p>
  <p><div class=rbscript>begin<br>
  &nbsp; file = open("some_file")<br>
  rescue<br>
  &nbsp; file = STDIN<br>
  end<br>
  <br>
  begin<br>
  &nbsp; # ... process the input ...<br>
  rescue<br>
  &nbsp; # ... and deal with any other exceptions here.<br>
  end</div>

  <p><code>retry</code> can be used in the <code>rescue</code> code to start the
  <code>begin</code> code over again.  It lets us rewrite the previous
  example a little more compactly:</p>
  <p><div class=rbscript>fname = "some_file"<br>
  begin<br>
  &nbsp; file = open(fname)<br>
  &nbsp; # ... process the input ...<br>
  rescue<br>
  &nbsp; fname = "STDIN"<br>
  &nbsp; retry<br>
  end</div>

  <p>However, there is a flaw here.  A nonexistent file will make
  this code retry in an infinite loop.  You need to watch out for
  such pitfalls when using <code>retry</code> for exception processing. </p>
  <p>Every ruby library raises an exception if any error occurs, and you
  can raise exceptions explicitly in your code too.  To raise an
  exception, use <code>raise</code>.  It takes one argument, which
  should be a string that describes the exception.  The argument is
  optional but should not be omitted.  It can be accessed later via
  the special global variable <code>$!</code>.</p>
  <p><div class=shell>ruby&gt;<font color="#ffff00"><b> raise "test error"</b></font><br>
  <font color="#50ffff"><b>&nbsp;&nbsp; test error</b></font><br>
  ruby&gt;<font color="#ffff00"><b> begin</b></font><br>
  &nbsp; &nbsp; |<font color="#ffff00"><b>&nbsp;&nbsp; raise "test2"</b></font><br>
  &nbsp; &nbsp; |<font color="#ffff00"><b> rescue</b></font><br>
  &nbsp; &nbsp; |<font color="#ffff00"><b>&nbsp;&nbsp; puts "An error occurred: #{$!}"</b></font><br>
  &nbsp; &nbsp; |<font color="#ffff00"><b> end</b></font><br>
  An error occurred: test2<br>
  <font color="#50ffff"><b>&nbsp;&nbsp; nil</b></font></div>


</section>
